# Generated by Django 4.2.23 on 2025-08-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateField(blank=True, null=True)),
                ('Booking_time', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('Payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('Created_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=30, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Specialization', models.CharField(blank=True, max_length=80, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=80, null=True)),
                ('Experience_year', models.IntegerField(blank=True, null=True)),
                ('E_mail', models.CharField(blank=True, max_length=80, null=True)),
                ('Phone', models.BigIntegerField(blank=True, max_length=15, null=True)),
                ('Added_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=30, null=True)),
                ('Registration_no', models.CharField(blank=True, max_length=30, null=True)),
                ('E_mail', models.CharField(blank=True, max_length=30, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('State', models.CharField(blank=True, max_length=30, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=30, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('E_mail', models.CharField(blank=True, max_length=30, null=True)),
                ('Phone', models.BigIntegerField(blank=True, max_length=15, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('State', models.CharField(blank=True, max_length=30, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(blank=True, null=True)),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_of_week', models.CharField(blank=True, max_length=30, null=True)),
                ('Start_Time', models.DateTimeField(blank=True, null=True)),
                ('End_Time', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('DOCTOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.doctortable')),
                ('HOSPITAL', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.hospitaltable')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('Advice', models.CharField(blank=True, max_length=100, null=True)),
                ('Next_visit_date', models.DateField(blank=True, null=True)),
                ('Created_on', models.DateTimeField(blank=True, null=True)),
                ('BOOKING', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.bookingtable')),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='hospitaltable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.logintable'),
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Specialization', models.CharField(blank=True, max_length=30, null=True)),
                ('Comment', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('DOCTOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.doctortable')),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='doctortable',
            name='HOSPITAL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.hospitaltable'),
        ),
        migrations.AddField(
            model_name='doctortable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.logintable'),
        ),
        migrations.CreateModel(
            name='ComplaintTbale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Against', models.CharField(blank=True, max_length=30, null=True)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Response', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='DOCTOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.doctortable'),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.usertable'),
        ),
    ]
