# Generated by Django 4.2.23 on 2025-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortable',
            name='Phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='Phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
