# Generated by Django 4.2.23 on 2025-08-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_alter_doctortable_phone_alter_usertable_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='Type',
            new_name='UserType',
        ),
    ]
