# Generated by Django 4.2.23 on 2025-08-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_rename_complainttbale_complainttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=30, null=True)),
                ('Registration_no', models.CharField(blank=True, max_length=30, null=True)),
                ('E_mail', models.CharField(blank=True, max_length=30, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('State', models.CharField(blank=True, max_length=30, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctortable',
            name='Added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
