# Generated by Django 4.2.23 on 2025-08-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_viewprofile_alter_doctortable_added_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viewProfile',
        ),
    ]
