# Generated by Django 4.2.23 on 2025-08-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_delete_viewprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainttable',
            name='Against',
        ),
        migrations.RemoveField(
            model_name='complainttable',
            name='Status',
        ),
        migrations.AddField(
            model_name='complainttable',
            name='HOSPIAL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.hospitaltable'),
        ),
    ]
