# Generated by Django 4.2.23 on 2025-08-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0009_rename_hospial_complainttable_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletable',
            name='HOSPITAL',
        ),
    ]
