# Generated by Django 4.2.23 on 2025-08-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0010_remove_scheduletable_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletable',
            name='Status',
        ),
    ]
