# Generated by Django 4.2.23 on 2025-08-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0012_alter_scheduletable_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaltable',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
