# Generated by Django 4.2.23 on 2025-11-22 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0018_remove_hospitaltable_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='Booking_time',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='DOCTOR',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='Payment_mode',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='Payment_status',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='SCHEDULEID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.scheduletable'),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='Created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
