# Generated by Django 4.2.23 on 2025-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0020_alter_bookingtable_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='Booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
