# Generated by Django 4.2.23 on 2025-11-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0021_alter_bookingtable_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='count',
        ),
    ]
