# Generated by Django 4.2.23 on 2025-11-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0022_remove_bookingtable_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='Booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
