# Generated by Django 4.2.23 on 2025-11-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0023_bookingtable_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='Booking_date',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='Booking_time',
        ),
    ]
