# Generated by Django 4.2.23 on 2025-11-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0024_remove_bookingtable_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='Booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
