# Generated by Django 4.2.23 on 2025-11-27 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0025_bookingtable_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='Specialization',
        ),
        migrations.RemoveField(
            model_name='feedbacktable',
            name='Status',
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
