# Generated by Django 4.2.23 on 2025-08-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_rename_type_logintable_usertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplaintTbale',
            new_name='ComplaintTable',
        ),
    ]
