# Generated by Django 4.2.23 on 2025-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0007_remove_complainttable_against_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainttable',
            name='Date',
            field=models.DateField(auto_now_add=True, default='2025-08-10'),
            preserve_default=False,
        ),
    ]
