# Generated by Django 4.2.23 on 2025-08-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0008_complainttable_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainttable',
            old_name='HOSPIAL',
            new_name='HOSPITAL',
        ),
    ]
