# Generated by Django 4.2.23 on 2025-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0011_remove_scheduletable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletable',
            name='End_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletable',
            name='Start_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
