# Generated by Django 4.2.23 on 2025-09-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0013_hospitaltable_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='Created_on',
        ),
    ]
