# Generated by Django 4.2.23 on 2025-09-08 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0014_remove_prescription_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='Created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
