# Generated by Django 4.2.23 on 2025-09-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0015_prescription_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
