# Generated by Django 4.2.23 on 2025-09-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0016_alter_usertable_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaltable',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltable',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
