# Generated by Django 4.2.23 on 2025-09-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0017_hospitaltable_latitude_hospitaltable_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaltable',
            name='Registration_no',
        ),
    ]
