# Generated by Django 4.2.23 on 2025-11-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0019_remove_bookingtable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='Booking_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
